### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by KetchuppOfficial** [vvit19/Stack#1]
Hi, vvit19!

I tried to build you program and failed. As far as there is no README provided, I simply ran **make** without any options. The result happend to be disappointing:

![image](https://github.com/vvit19/Stack/assets/83651035/b8778802-6aa2-4a04-b973-1efd2b383a77)

With best regards, KetchuppOfficial

**Comment by vvit19** [comment]
Hello) thank you for this remark, I've changed makefile so now you can run program with make (and then ./stack), unfortunately I can't write README now because of physics, but I think I'll do it in my next project spu.
