### ISSUE TITLE
Oops... Segfault

### ISSUE THREAD

**Issue by KetchuppOfficial** [vvit19/Stack#2]
Hi, vvit19!

I crushed your program with segmentation fault :)

```C
#include <stdio.h>

#include "stack.h"

int main()
{
    stack stk = {};

    STACK_CTOR(&stk);

    stack_push(&stk, 0);
    stack_pop(&stk, NULL);

    stack_dtor(&stk);
}
```

![image](https://github.com/vvit19/Stack/assets/83651035/0f3b96a7-12ad-4a06-8b60-590644aeaad7)

Hope general physics won't stand in the way of the good code.

With best regards, KetchuppOfficial

**Comment by vvit19** [comment]
Hello, Ketchupp! 
Well, that's really segfault, but it was an accident, so now there are not any other vulnerabilities (at least I think so), and yes, physics sucks so it won't stand on my way. 
With best regards)
